// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @weights_proj(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<f32, gm>, %arg3: i32, %arg4: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c262144 = arith.constant 262144 : index
  %c0_i64 = arith.constant 0 : i64
  %c16384_i64 = arith.constant 16384 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c8 = arith.constant 8 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c64 = arith.constant 64 : index
  %c1024 = arith.constant 1024 : index
  %c16 = arith.constant 16 : index
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c512 = arith.constant 512 : index
  %c256 = arith.constant 256 : index
  %c32768 = arith.constant 32768 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c8, %c4096], strides = [%c32768, %c32768, %c32768, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c4096, %c64], strides = [%c262144, %c262144, %c262144, %c64, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c64, %c64], strides = [%c4096, %c4096, %c4096, %c64, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %3 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %4 = arith.index_cast %arg3 : i32 to index
  %5 = arith.muli %4, %c1024 : index
  %6 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  scf.for %arg5 = %c0 to %c2 step %c1 {
    %9 = arith.muli %arg5, %c512 : index
    %10 = arith.addi %5, %9 : index
    %11 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c512 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %12 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %10], sizes = [%c1, %c1, %c1, %c8, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%12 : !pto.partition_tensor_view<1x1x1x8x512xbf16>) outs(%11 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %13 = pto.alloc_tile addr = %c16384_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %14 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %10, %c0], sizes = [%c1, %c1, %c1, %c512, %c64] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%14 : !pto.partition_tensor_view<1x1x1x512x64xbf16>) outs(%13 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %15 = arith.cmpi eq, %arg5, %c0 : index
    scf.if %15 {
      %16 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %17 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%11, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%17 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %18 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%13, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%18 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %19 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%11, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%19 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %20 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%13, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%20 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %21 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%17, %18 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%21 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %22 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%22, %19, %20 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%22 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    } else {
      %16 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%11, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%16 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %17 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%13, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%17 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %18 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%11, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%18 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %19 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%13, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%19 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %20 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%20, %16, %17 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%20 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %21 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%21, %18, %19 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%21 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
  }
  %7 = arith.muli %4, %c16 : index
  %8 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %7, %c0], sizes = [%c1, %c1, %c1, %c16, %c64] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%6 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%8 : !pto.partition_tensor_view<1x1x1x16x64xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

