// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @proj_a_mm(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<f32, gm>, %arg3: index, %arg4: index, %arg5: index, %arg6: index) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c33554432 = arith.constant 33554432 : index
  %c1048576 = arith.constant 1048576 : index
  %c131072_i64 = arith.constant 131072 : i64
  %c196608_i64 = arith.constant 196608 : i64
  %c0_i64 = arith.constant 0 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c65536_i64 = arith.constant 65536 : i64
  %c1024 = arith.constant 1024 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c128 = arith.constant 128 : index
  %c8192 = arith.constant 8192 : index
  %c256 = arith.constant 256 : index
  %c0 = arith.constant 0 : index
  %c15 = arith.constant 15 : index
  %c2 = arith.constant 2 : index
  %c3840 = arith.constant 3840 : index
  %c4194304 = arith.constant 4194304 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c1024, %c4096], strides = [%c4194304, %c4194304, %c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c8, %c1024, %c4096], strides = [%c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<?x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c128, %c8192], strides = [%c1048576, %c1048576, %c1048576, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %3 = pto.alloc_tile addr = %c131072_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %4 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %c0], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%4 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%3 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %5 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %6 = pto.alloc_tile addr = %c196608_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %7 = arith.muli %arg4, %c1024 : index
  %8 = arith.addi %7, %arg5 : index
  %9 = pto.partition_view %5, offsets = [%c0, %c0, %c0, %8, %c0], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%9 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%6 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %10 = pto.alloc_tile addr = %c196608_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
  %11 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%3, %c0, %c0 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%12 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %13 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%10, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%13 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %14 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%3, %c0, %c128 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%14 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %15 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%10, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%15 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %16 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul ins(%12, %13 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%16 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %17 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%17, %14, %15 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%17 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  scf.for %arg7 = %c1 to %c15 step %c2 {
    %36 = arith.muli %arg7, %c256 : index
    %37 = arith.muli %arg7, %c256 : index
    %38 = arith.addi %37, %c256 : index
    %39 = pto.alloc_tile addr = %c131072_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %40 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %36], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%40 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%39 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %41 = pto.alloc_tile addr = %c196608_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %42 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %38], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%42 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%41 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %43 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
    %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %45 = arith.muli %arg4, %c1024 : index
    %46 = arith.addi %45, %arg5 : index
    %47 = pto.partition_view %43, offsets = [%c0, %c0, %c0, %46, %36], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%47 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%44 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %48 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
    %49 = pto.alloc_tile addr = %c65536_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %50 = arith.muli %arg4, %c1024 : index
    %51 = arith.addi %50, %arg5 : index
    %52 = pto.partition_view %48, offsets = [%c0, %c0, %c0, %51, %38], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%52 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%49 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %53 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
    %54 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%39, %c0, %c0 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%54 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %55 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%53, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%55 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %56 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%39, %c0, %c128 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%56 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %57 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%53, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%57 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %58 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%58, %54, %55 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%58 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %59 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%59, %56, %57 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%59 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %60 = pto.alloc_tile addr = %c65536_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
    %61 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%41, %c0, %c0 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%61 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%60, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%62 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %63 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%41, %c0, %c128 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%63 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %64 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%60, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%64 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %65 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%65, %61, %62 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%65 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %66 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%66, %63, %64 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%66 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  %18 = pto.alloc_tile addr = %c131072_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %19 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %c3840], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%19 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%18 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %20 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %21 = pto.alloc_tile addr = %c196608_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %22 = arith.muli %arg4, %c1024 : index
  %23 = arith.addi %22, %arg5 : index
  %24 = pto.partition_view %20, offsets = [%c0, %c0, %c0, %23, %c3840], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%24 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%21 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %25 = pto.alloc_tile addr = %c196608_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
  %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%18, %c0, %c0 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%25, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%27 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %28 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%18, %c0, %c128 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%28 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %29 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%25, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%29 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %30 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%30, %26, %27 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%30 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %31 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%31, %28, %29 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%31 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %32 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %34 = arith.addi %arg6, %arg5 : index
  %35 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %c0, %34], sizes = [%c1, %c1, %c1, %c128, %c128] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%33 : !pto.tile_buf<acc, 128x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%35 : !pto.partition_tensor_view<1x1x1x128x128xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

