// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @qproj_matmul(%arg0: !pto.ptr<i32, gm>, %arg1: !pto.ptr<i8, gm>, %arg2: !pto.ptr<i8, gm>, %arg3: index, %arg4: i32, %arg5: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c33554432 = arith.constant 33554432 : index
  %c131072 = arith.constant 131072 : index
  %c0_i64 = arith.constant 0 : i64
  %c2048_i64 = arith.constant 2048 : i64
  %c133120_i64 = arith.constant 133120 : i64
  %c135168_i64 = arith.constant 135168 : i64
  %c1536_i64 = arith.constant 1536 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c512_i64 = arith.constant 512 : i64
  %c1024_i64 = arith.constant 1024 : i64
  %c128 = arith.constant 128 : index
  %c32768 = arith.constant 32768 : index
  %c1 = arith.constant 1 : index
  %c1024 = arith.constant 1024 : index
  %c2 = arith.constant 2 : index
  %c0 = arith.constant 0 : index
  %c16 = arith.constant 16 : index
  %c8 = arith.constant 8 : index
  %c64 = arith.constant 64 : index
  %c32 = arith.constant 32 : index
  %c4194304 = arith.constant 4194304 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c128, %c32768], strides = [%c4194304, %c4194304, %c4194304, %c32768, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi32>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c128, %c1024], strides = [%c131072, %c131072, %c131072, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c1024, %c32768], strides = [%c33554432, %c33554432, %c33554432, %c32768, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %3 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %4 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %5 = arith.index_cast %arg4 : i32 to index
  %6 = arith.muli %5, %c2 : index
  scf.for %arg6 = %c0 to %c2 step %c1 {
    %7 = arith.addi %6, %arg6 : index
    %8 = arith.muli %7, %c1024 : index
    %9 = arith.divsi %arg3, %c16 : index
    scf.for %arg7 = %c0 to %9 step %c1 {
      %10 = arith.muli %arg7, %c16 : index
      %11 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      scf.for %arg8 = %c0 to %c8 step %c2 {
        %13 = arith.muli %arg8, %c128 : index
        %14 = arith.muli %arg8, %c128 : index
        %15 = arith.addi %14, %c128 : index
        %16 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %17 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %10, %13], sizes = [%c1, %c1, %c1, %c16, %c128] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%17 : !pto.partition_tensor_view<1x1x1x16x128xi8>) outs(%16 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %18 = pto.alloc_tile addr = %c2048_i64 valid_row = %c128 valid_col = %c1024 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %19 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %13, %8], sizes = [%c1, %c1, %c1, %c128, %c1024] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%19 : !pto.partition_tensor_view<1x1x1x128x1024xi8>) outs(%18 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %20 = pto.alloc_tile addr = %c133120_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %21 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %10, %15], sizes = [%c1, %c1, %c1, %c16, %c128] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%21 : !pto.partition_tensor_view<1x1x1x16x128xi8>) outs(%20 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %22 = pto.alloc_tile addr = %c135168_i64 valid_row = %c128 valid_col = %c1024 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %23 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %15, %8], sizes = [%c1, %c1, %c1, %c128, %c1024] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%23 : !pto.partition_tensor_view<1x1x1x128x1024xi8>) outs(%22 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %24 = arith.cmpi eq, %13, %c0 : index
        scf.if %24 {
          %25 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          scf.for %arg9 = %c0 to %c128 step %c64 {
            %26 = pto.alloc_tile addr = %c1536_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
            pto.textract ins(%16, %c0, %arg9 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
            pto.textract ins(%18, %arg9, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%27 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %28 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
            %29 = arith.addi %arg9, %c32 : index
            pto.textract ins(%16, %c0, %29 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%28 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %30 = pto.alloc_tile addr = %c32768_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
            %31 = arith.addi %arg9, %c32 : index
            pto.textract ins(%18, %31, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%30 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %32 = arith.cmpi eq, %arg9, %c0 : index
            scf.if %32 {
              %34 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
              pto.tmatmul ins(%26, %27 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%34 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            } else {
              %34 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
              pto.tmatmul.acc ins(%34, %26, %27 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%34 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            }
            %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
            pto.tmatmul.acc ins(%33, %28, %30 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%33 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          }
        } else {
          scf.for %arg9 = %c0 to %c128 step %c64 {
            %25 = pto.alloc_tile addr = %c1536_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
            pto.textract ins(%16, %c0, %arg9 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%25 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
            pto.textract ins(%18, %arg9, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
            %28 = arith.addi %arg9, %c32 : index
            pto.textract ins(%16, %c0, %28 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%27 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %29 = pto.alloc_tile addr = %c32768_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
            %30 = arith.addi %arg9, %c32 : index
            pto.textract ins(%18, %30, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%29 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %31 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
            pto.tmatmul.acc ins(%31, %25, %26 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%31 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
            %32 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
            pto.tmatmul.acc ins(%32, %27, %29 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%32 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          }
        }
        scf.for %arg9 = %c0 to %c128 step %c64 {
          %25 = pto.alloc_tile addr = %c512_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
          pto.textract ins(%20, %c0, %arg9 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%25 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
          pto.textract ins(%22, %arg9, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %27 = pto.alloc_tile addr = %c1024_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>
          %28 = arith.addi %arg9, %c32 : index
          pto.textract ins(%20, %c0, %28 : !pto.tile_buf<mat, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%27 : !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %29 = pto.alloc_tile addr = %c32768_i64 valid_row = %c32 valid_col = %c1024 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>
          %30 = arith.addi %arg9, %c32 : index
          pto.textract ins(%22, %30, %c0 : !pto.tile_buf<mat, 128x1024xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%29 : !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %31 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%31, %25, %26 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%31 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %32 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c1024 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%32, %27, %29 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x32xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x1024xi8, valid=?x?, slayout=col_major>) outs(%32 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
      }
      %12 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %10, %8], sizes = [%c1, %c1, %c1, %c16, %c1024] : !pto.tensor_view<1x1x1x?x?xi32>
      pto.tstore ins(%11 : !pto.tile_buf<acc, 16x1024xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%12 : !pto.partition_tensor_view<1x1x1x16x1024xi32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
  }
  return
}

