// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @prefill_idx_weights_proj_aic(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<f32, gm>, %arg3: i32, %arg4: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c8192 = arith.constant 8192 : index
  %c262144 = arith.constant 262144 : index
  %c0_i64 = arith.constant 0 : i64
  %c2048_i64 = arith.constant 2048 : i64
  %c6144_i64 = arith.constant 6144 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c128 = arith.constant 128 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c64 = arith.constant 64 : index
  %c32 = arith.constant 32 : index
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c524288 = arith.constant 524288 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c128, %c4096], strides = [%c524288, %c524288, %c524288, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c4096, %c64], strides = [%c262144, %c262144, %c262144, %c64, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c128, %c64], strides = [%c8192, %c8192, %c8192, %c64, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %3 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %4 = pto.import_reserved_buffer{name = "prefill_idx_weights_proj_c2v_slot_buffer", peer_func = @prefill_idx_weights_proj_aiv} -> i32
  %5 = pto.initialize_l2l_pipe{dir_mask = 1, slot_size = 8192, slot_num = 8, nosplit = true} (%4 : i32) {__pto.frontend_id = 0 : i32} -> !pto.pipe
  %6 = arith.index_cast %arg3 : i32 to index
  %7 = arith.muli %6, %c32 : index
  %8 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  scf.for %arg5 = %c0 to %c128 step %c2 {
    %9 = arith.muli %arg5, %c32 : index
    %10 = arith.muli %arg5, %c32 : index
    %11 = arith.addi %10, %c32 : index
    %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %13 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %7, %9], sizes = [%c1, %c1, %c1, %c32, %c32] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%13 : !pto.partition_tensor_view<1x1x1x32x32xbf16>) outs(%12 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %14 = pto.alloc_tile addr = %c2048_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %15 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %9, %c0], sizes = [%c1, %c1, %c1, %c32, %c64] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%15 : !pto.partition_tensor_view<1x1x1x32x64xbf16>) outs(%14 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %16 = pto.alloc_tile addr = %c6144_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %17 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %7, %11], sizes = [%c1, %c1, %c1, %c32, %c32] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%17 : !pto.partition_tensor_view<1x1x1x32x32xbf16>) outs(%16 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %18 = pto.alloc_tile addr = %c8192_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %19 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %11, %c0], sizes = [%c1, %c1, %c1, %c32, %c64] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%19 : !pto.partition_tensor_view<1x1x1x32x64xbf16>) outs(%18 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %20 = arith.cmpi eq, %9, %c0 : index
    scf.if %20 {
      %24 = pto.alloc_tile addr = %c2048_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tmov ins(%12 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%24 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %25 = pto.alloc_tile addr = %c4096_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%14 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%25 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%24, %25 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) outs(%26 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    } else {
      %24 = pto.alloc_tile addr = %c2048_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tmov ins(%12 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%24 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %25 = pto.alloc_tile addr = %c4096_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%14 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%25 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%26, %24, %25 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) outs(%26 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %21 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%16 : !pto.tile_buf<mat, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%21 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %22 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>
    pto.tmov ins(%18 : !pto.tile_buf<mat, 32x64xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%22 : !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %23 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c64 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%23, %21, %22 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x64xbf16, valid=?x?, slayout=col_major>) outs(%23 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  pto.tpush(%8, %5 : !pto.tile_buf<acc, 32x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.pipe) {split = 0}
  return
}

