// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @qr_proj_matmul(%arg0: !pto.ptr<f32, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<bf16, gm>, %arg3: index, %arg4: index, %arg5: index, %arg6: i32, %arg7: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c4194304 = arith.constant 4194304 : index
  %c0_i64 = arith.constant 0 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c73728_i64 = arith.constant 73728 : i64
  %c81920_i64 = arith.constant 81920 : i64
  %c12288_i64 = arith.constant 12288 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c128 = arith.constant 128 : index
  %c1024 = arith.constant 1024 : index
  %c1 = arith.constant 1 : index
  %c4096 = arith.constant 4096 : index
  %c2 = arith.constant 2 : index
  %c2048 = arith.constant 2048 : index
  %c0 = arith.constant 0 : index
  %c16 = arith.constant 16 : index
  %c8 = arith.constant 8 : index
  %c256 = arith.constant 256 : index
  %c131072 = arith.constant 131072 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c128, %c1024], strides = [%c131072, %c131072, %c131072, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %1 = arith.muli %arg5, %c4096 : index
  %2 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %arg5, %c4096], strides = [%1, %1, %1, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %3 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c4096, %c1024], strides = [%c4194304, %c4194304, %c4194304, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %4 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %5 = arith.index_cast %arg6 : i32 to index
  %6 = arith.divsi %5, %c2 : index
  %7 = arith.muli %6, %c128 : index
  %8 = arith.remsi %5, %c2 : index
  %9 = arith.muli %8, %c2048 : index
  %10 = arith.divsi %arg3, %c16 : index
  scf.for %arg8 = %c0 to %10 step %c1 {
    %11 = arith.muli %arg8, %c16 : index
    %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    scf.for %arg9 = %c0 to %c8 step %c2 {
      %14 = arith.muli %arg9, %c256 : index
      %15 = arith.addi %9, %14 : index
      %16 = arith.subi %arg5, %11 : index
      %17 = arith.minsi %16, %c16 : index
      %18 = arith.muli %arg9, %c256 : index
      %19 = arith.addi %18, %c256 : index
      %20 = arith.addi %9, %19 : index
      %21 = arith.subi %arg5, %11 : index
      %22 = arith.minsi %21, %c16 : index
      %23 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %24 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %15], sizes = [%c1, %c1, %c1, %17, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%24 : !pto.partition_tensor_view<1x1x1x?x256xbf16>) outs(%23 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %25 = pto.alloc_tile addr = %c8192_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %26 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %15, %7], sizes = [%c1, %c1, %c1, %c256, %c128] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%26 : !pto.partition_tensor_view<1x1x1x256x128xbf16>) outs(%25 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %27 = pto.alloc_tile addr = %c73728_i64 valid_row = %22 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %28 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %20], sizes = [%c1, %c1, %c1, %22, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%28 : !pto.partition_tensor_view<1x1x1x?x256xbf16>) outs(%27 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %29 = pto.alloc_tile addr = %c81920_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %30 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %20, %7], sizes = [%c1, %c1, %c1, %c256, %c128] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%30 : !pto.partition_tensor_view<1x1x1x256x128xbf16>) outs(%29 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %31 = arith.cmpi eq, %arg9, %c0 : index
      scf.if %31 {
        %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        %39 = pto.alloc_tile addr = %c12288_i64 valid_row = %17 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%23, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%39 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%25, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%40 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%23, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%41 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %42 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%25, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%42 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %43 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul ins(%39, %40 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%43 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%44, %41, %42 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%44 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      } else {
        %38 = pto.alloc_tile addr = %c12288_i64 valid_row = %17 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%23, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%38 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%25, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%39 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %40 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%23, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%40 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%25, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%41 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %42 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%42, %38, %39 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%42 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %43 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%43, %40, %41 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%43 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      %32 = pto.alloc_tile addr = %c4096_i64 valid_row = %22 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%27, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%32 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%29, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%33 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %34 = pto.alloc_tile addr = %c8192_i64 valid_row = %22 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%27, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%34 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %35 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%29, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %36 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%36, %32, %33 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%36 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %37 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%37, %34, %35 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%37 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %13 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %11, %7], sizes = [%c1, %c1, %c1, %c16, %c128] : !pto.tensor_view<1x1x1x?x?xf32>
    pto.tstore ins(%12 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%13 : !pto.partition_tensor_view<1x1x1x16x128xf32>) {atomicType = #pto<atomic_type atomic_add>, candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  return
}
