// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @kv_score_proj(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<bf16, gm>, %arg3: !pto.ptr<f32, gm>, %arg4: !pto.ptr<f32, gm>, %arg5: i32, %arg6: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c16384 = arith.constant 16384 : index
  %c4194304 = arith.constant 4194304 : index
  %c0_i64 = arith.constant 0 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c147456_i64 = arith.constant 147456 : i64
  %c163840_i64 = arith.constant 163840 : i64
  %c229376_i64 = arith.constant 229376 : i64
  %c16384_i64 = arith.constant 16384 : i64
  %c81920_i64 = arith.constant 81920 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c24576_i64 = arith.constant 24576 : i64
  %c8 = arith.constant 8 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c1024 = arith.constant 1024 : index
  %c16 = arith.constant 16 : index
  %c64 = arith.constant 64 : index
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c512 = arith.constant 512 : index
  %c256 = arith.constant 256 : index
  %c32768 = arith.constant 32768 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c8, %c4096], strides = [%c32768, %c32768, %c32768, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c1024, %c4096], strides = [%c4194304, %c4194304, %c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c1024, %c4096], strides = [%c4194304, %c4194304, %c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %3 = pto.make_tensor_view %arg3, shape = [%c1, %c1, %c1, %c16, %c1024], strides = [%c16384, %c16384, %c16384, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %4 = pto.make_tensor_view %arg4, shape = [%c1, %c1, %c1, %c16, %c1024], strides = [%c16384, %c16384, %c16384, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %5 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %6 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %7 = arith.index_cast %arg5 : i32 to index
  %8 = arith.divsi %7, %c16 : index
  %9 = arith.muli %8, %c16 : index
  %10 = arith.remsi %7, %c16 : index
  %11 = arith.muli %10, %c64 : index
  %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %13 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  scf.for %arg7 = %c0 to %c8 step %c2 {
    %16 = arith.muli %arg7, %c512 : index
    %17 = arith.subi %c8, %9 : index
    %18 = arith.muli %arg7, %c512 : index
    %19 = arith.addi %18, %c512 : index
    %20 = arith.subi %c8, %9 : index
    %21 = pto.alloc_tile addr = %c147456_i64 valid_row = %17 valid_col = %c512 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %22 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %9, %16], sizes = [%c1, %c1, %c1, %17, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x?x512xbf16>) outs(%21 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %23 = pto.alloc_tile addr = %c163840_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %24 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %11, %16], sizes = [%c1, %c1, %c1, %c64, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%24 : !pto.partition_tensor_view<1x1x1x64x512xbf16>) outs(%23 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %25 = pto.alloc_tile addr = %c229376_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %26 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %16], sizes = [%c1, %c1, %c1, %c64, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%26 : !pto.partition_tensor_view<1x1x1x64x512xbf16>) outs(%25 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %27 = pto.alloc_tile addr = %c0_i64 valid_row = %20 valid_col = %c512 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %28 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %9, %19], sizes = [%c1, %c1, %c1, %20, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%28 : !pto.partition_tensor_view<1x1x1x?x512xbf16>) outs(%27 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %29 = pto.alloc_tile addr = %c16384_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %30 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %11, %19], sizes = [%c1, %c1, %c1, %c64, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%30 : !pto.partition_tensor_view<1x1x1x64x512xbf16>) outs(%29 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %31 = pto.alloc_tile addr = %c81920_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %32 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %19], sizes = [%c1, %c1, %c1, %c64, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%32 : !pto.partition_tensor_view<1x1x1x64x512xbf16>) outs(%31 : !pto.tile_buf<mat, 64x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %33 = arith.cmpi eq, %16, %c0 : index
    scf.if %33 {
      %48 = pto.alloc_tile addr = %c163840_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
      %49 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %50 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%50 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %51 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%48, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%51 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %52 = pto.alloc_tile addr = %c8192_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%52 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %53 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%48, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%53 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %54 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%50, %51 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%54 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %55 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%55, %52, %53 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%55 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %56 = pto.alloc_tile addr = %c229376_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
      %57 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %58 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%58 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %59 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%56, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%59 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %60 = pto.alloc_tile addr = %c8192_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%60 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %61 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%56, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%61 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %62 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%58, %59 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%62 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %63 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%63, %60, %61 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%63 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    } else {
      %48 = pto.alloc_tile addr = %c163840_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
      %49 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%49 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %50 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%48, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%50 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %51 = pto.alloc_tile addr = %c8192_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%51 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %52 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%48, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%52 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %53 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%53, %49, %50 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%53 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %54 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%54, %51, %52 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%54 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %55 = pto.alloc_tile addr = %c229376_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
      %56 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%56 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %57 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%55, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%57 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %58 = pto.alloc_tile addr = %c8192_i64 valid_row = %17 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%21, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%58 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %59 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%55, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%59 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %60 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%60, %56, %57 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%60 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %61 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%61, %58, %59 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%61 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %34 = pto.alloc_tile addr = %c16384_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
    %35 = pto.alloc_tile addr = %c16384_i64 valid_row = %20 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%27, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %36 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%34, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%36 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %37 = pto.alloc_tile addr = %c24576_i64 valid_row = %20 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%27, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %38 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%34, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%38 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%39, %35, %36 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%40, %37, %38 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %41 = pto.alloc_tile addr = %c81920_i64 valid_row = %c512 valid_col = %c64 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>
    %42 = pto.alloc_tile addr = %c16384_i64 valid_row = %20 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%27, %c0, %c0 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%42 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %43 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%41, %c0, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%43 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %44 = pto.alloc_tile addr = %c24576_i64 valid_row = %20 valid_col = %c256 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%27, %c0, %c256 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%44 : !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %45 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c64 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%41, %c256, %c0 : !pto.tile_buf<mat, 512x64xbf16, valid=?x?, slayout=col_major>, index, index) outs(%45 : !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %46 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%46, %42, %43 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%46 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %47 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c64 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%47, %44, %45 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x64xbf16, valid=?x?, slayout=col_major>) outs(%47 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  %14 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %9, %11], sizes = [%c1, %c1, %c1, %c16, %c64] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%12 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%14 : !pto.partition_tensor_view<1x1x1x16x64xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %15 = pto.partition_view %4, offsets = [%c0, %c0, %c0, %9, %11], sizes = [%c1, %c1, %c1, %c16, %c64] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%13 : !pto.tile_buf<acc, 16x64xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%15 : !pto.partition_tensor_view<1x1x1x16x64xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

