// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @proj_b_mm(%arg0: !pto.ptr<i32, gm>, %arg1: !pto.ptr<i8, gm>, %arg2: !pto.ptr<i8, gm>, %arg3: index, %arg4: index, %arg5: index, %arg6: i32, %arg7: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c33554432 = arith.constant 33554432 : index
  %c131072 = arith.constant 131072 : index
  %c0_i64 = arith.constant 0 : i64
  %c69632_i64 = arith.constant 69632 : i64
  %c73728_i64 = arith.constant 73728 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c6144_i64 = arith.constant 6144 : i64
  %c2048_i64 = arith.constant 2048 : i64
  %c16 = arith.constant 16 : index
  %c32768 = arith.constant 32768 : index
  %c1 = arith.constant 1 : index
  %c8192 = arith.constant 8192 : index
  %c4096 = arith.constant 4096 : index
  %c512 = arith.constant 512 : index
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c256 = arith.constant 256 : index
  %c4 = arith.constant 4 : index
  %c128 = arith.constant 128 : index
  %c524288 = arith.constant 524288 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c16, %c32768], strides = [%c524288, %c524288, %c524288, %c32768, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi32>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c16, %c8192], strides = [%c131072, %c131072, %c131072, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c4096, %c8192], strides = [%c33554432, %c33554432, %c33554432, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %3 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %4 = arith.index_cast %arg6 : i32 to index
  %5 = arith.muli %4, %c512 : index
  %6 = scf.for %arg8 = %c0 to %c2 step %c1 iter_args(%arg9 = %arg3) -> (index) {
    %7 = arith.muli %arg8, %c256 : index
    %8 = arith.addi %5, %7 : index
    %9 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    scf.for %arg10 = %c0 to %c4 step %c2 {
      %13 = arith.muli %arg10, %c256 : index
      %14 = arith.addi %arg4, %13 : index
      %15 = arith.muli %arg10, %c256 : index
      %16 = arith.addi %15, %c256 : index
      %17 = arith.addi %arg4, %16 : index
      %18 = arith.cmpi eq, %arg10, %c0 : index
      scf.if %18 {
        %30 = pto.alloc_tile addr = %c69632_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %31 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %arg4], sizes = [%c1, %c1, %c1, %c16, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%31 : !pto.partition_tensor_view<1x1x1x16x256xi8>) outs(%30 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %32 = pto.alloc_tile addr = %c73728_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %33 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %8, %arg4], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%33 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%32 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %34 = pto.alloc_tile addr = %c73728_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
        %35 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        %36 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%30, %c0, %c0 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%36 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %37 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
        pto.textract ins(%34, %c0, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%37 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %38 = pto.alloc_tile addr = %c6144_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%30, %c0, %c128 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%38 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
        pto.textract ins(%34, %c128, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%39 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul ins(%36, %37 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%41, %38, %39 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%41 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      } else {
        %30 = pto.alloc_tile addr = %c69632_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %31 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %14], sizes = [%c1, %c1, %c1, %c16, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%31 : !pto.partition_tensor_view<1x1x1x16x256xi8>) outs(%30 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %32 = pto.alloc_tile addr = %c73728_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %33 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %8, %14], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
        pto.tload ins(%33 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%32 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %34 = pto.alloc_tile addr = %c73728_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
        %35 = pto.alloc_tile addr = %c4096_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%30, %c0, %c0 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %36 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
        pto.textract ins(%34, %c0, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%36 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %37 = pto.alloc_tile addr = %c6144_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%30, %c0, %c128 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
        pto.textract ins(%34, %c128, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%38 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%39, %35, %36 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%40, %37, %38 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      %19 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %20 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %17], sizes = [%c1, %c1, %c1, %c16, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%20 : !pto.partition_tensor_view<1x1x1x16x256xi8>) outs(%19 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %21 = pto.alloc_tile addr = %c4096_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %22 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %8, %17], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%21 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %23 = pto.alloc_tile addr = %c4096_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
      %24 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%19, %c0, %c0 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%24 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %25 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
      pto.textract ins(%23, %c0, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%25 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %26 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%19, %c0, %c128 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>
      pto.textract ins(%23, %c128, %c0 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>, index, index) outs(%27 : !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %28 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%28, %24, %25 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%28 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %29 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c256 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%29, %26, %27 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x256xi8, valid=?x?, slayout=col_major>) outs(%29 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %10 = arith.muli %arg5, %c4096 : index
    %11 = arith.addi %10, %8 : index
    %12 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %11], sizes = [%c1, %c1, %c1, %c16, %c256] : !pto.tensor_view<1x1x1x?x?xi32>
    pto.tstore ins(%9 : !pto.tile_buf<acc, 16x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%12 : !pto.partition_tensor_view<1x1x1x16x256xi32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    scf.yield %8 : index
  }
  return
}
