// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @prefill_c4_kv_score_proj(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<bf16, gm>, %arg3: !pto.ptr<f32, gm>, %arg4: !pto.ptr<f32, gm>, %arg5: i32, %arg6: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c131072 = arith.constant 131072 : index
  %c4194304 = arith.constant 4194304 : index
  %c0_i64 = arith.constant 0 : i64
  %c16384_i64 = arith.constant 16384 : i64
  %c196608_i64 = arith.constant 196608 : i64
  %c327680_i64 = arith.constant 327680 : i64
  %c360448_i64 = arith.constant 360448 : i64
  %c131072_i64 = arith.constant 131072 : i64
  %c163840_i64 = arith.constant 163840 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c24576_i64 = arith.constant 24576 : i64
  %c128 = arith.constant 128 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c1024 = arith.constant 1024 : index
  %c32 = arith.constant 32 : index
  %c0 = arith.constant 0 : index
  %c8 = arith.constant 8 : index
  %c2 = arith.constant 2 : index
  %c512 = arith.constant 512 : index
  %c256 = arith.constant 256 : index
  %c524288 = arith.constant 524288 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c128, %c4096], strides = [%c524288, %c524288, %c524288, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c1024, %c4096], strides = [%c4194304, %c4194304, %c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c1024, %c4096], strides = [%c4194304, %c4194304, %c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %3 = pto.make_tensor_view %arg3, shape = [%c1, %c1, %c1, %c128, %c1024], strides = [%c131072, %c131072, %c131072, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %4 = pto.make_tensor_view %arg4, shape = [%c1, %c1, %c1, %c128, %c1024], strides = [%c131072, %c131072, %c131072, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %5 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %6 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %7 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %8 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %9 = arith.index_cast %arg5 : i32 to index
  %10 = arith.muli %9, %c32 : index
  %11 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %12 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  scf.for %arg7 = %c0 to %c8 step %c2 {
    %15 = arith.muli %arg7, %c512 : index
    %16 = arith.muli %arg7, %c512 : index
    %17 = arith.addi %16, %c512 : index
    %18 = pto.alloc_tile addr = %c196608_i64 valid_row = %c128 valid_col = %c512 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %19 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %15], sizes = [%c1, %c1, %c1, %c128, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%19 : !pto.partition_tensor_view<1x1x1x128x512xbf16>) outs(%18 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %20 = pto.alloc_tile addr = %c327680_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %21 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %10, %15], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%21 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%20 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %22 = pto.alloc_tile addr = %c360448_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %23 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %10, %15], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%23 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%22 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %24 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c512 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %25 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %17], sizes = [%c1, %c1, %c1, %c128, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%25 : !pto.partition_tensor_view<1x1x1x128x512xbf16>) outs(%24 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %26 = pto.alloc_tile addr = %c131072_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %27 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %10, %17], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%27 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%26 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %28 = pto.alloc_tile addr = %c163840_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %29 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %10, %17], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%29 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%28 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %30 = arith.cmpi eq, %15, %c0 : index
    scf.if %30 {
      %33 = pto.alloc_tile addr = %c327680_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %34 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      scf.for %arg8 = %c0 to %c512 step %c256 {
        %37 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%18, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%33, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%38 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %40 = arith.addi %arg8, %c128 : index
        pto.textract ins(%18, %c0, %40 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%39 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c8192_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        %42 = arith.addi %arg8, %c128 : index
        pto.textract ins(%33, %42, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%41 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %43 = arith.cmpi eq, %arg8, %c0 : index
        scf.if %43 {
          %45 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%37, %38 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%45 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %45 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%45, %37, %38 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%45 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%44, %39, %41 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%44 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      %35 = pto.alloc_tile addr = %c360448_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %36 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      scf.for %arg8 = %c0 to %c512 step %c256 {
        %37 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%18, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%35, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%38 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %40 = arith.addi %arg8, %c128 : index
        pto.textract ins(%18, %c0, %40 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%39 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c8192_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        %42 = arith.addi %arg8, %c128 : index
        pto.textract ins(%35, %42, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%41 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %43 = arith.cmpi eq, %arg8, %c0 : index
        scf.if %43 {
          %45 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%37, %38 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%45 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %45 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%45, %37, %38 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%45 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %44 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%44, %39, %41 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%44 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
    } else {
      %33 = pto.alloc_tile addr = %c327680_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      scf.for %arg8 = %c0 to %c512 step %c256 {
        %35 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%18, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %36 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%33, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%36 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %37 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %38 = arith.addi %arg8, %c128 : index
        pto.textract ins(%18, %c0, %38 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c8192_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        %40 = arith.addi %arg8, %c128 : index
        pto.textract ins(%33, %40, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%39 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%41, %35, %36 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%41 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %42 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%42, %37, %39 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%42 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      %34 = pto.alloc_tile addr = %c360448_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      scf.for %arg8 = %c0 to %c512 step %c256 {
        %35 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%18, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %36 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%34, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%36 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %37 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %38 = arith.addi %arg8, %c128 : index
        pto.textract ins(%18, %c0, %38 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%37 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %39 = pto.alloc_tile addr = %c8192_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
        %40 = arith.addi %arg8, %c128 : index
        pto.textract ins(%34, %40, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%39 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %41 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%41, %35, %36 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%41 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %42 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%42, %37, %39 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%42 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
    }
    %31 = pto.alloc_tile addr = %c131072_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
    scf.for %arg8 = %c0 to %c512 step %c256 {
      %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%24, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%33 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %34 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%31, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%34 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %35 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %36 = arith.addi %arg8, %c128 : index
      pto.textract ins(%24, %c0, %36 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %37 = pto.alloc_tile addr = %c24576_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
      %38 = arith.addi %arg8, %c128 : index
      pto.textract ins(%31, %38, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%37 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%39, %33, %34 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%40, %35, %37 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %32 = pto.alloc_tile addr = %c163840_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
    scf.for %arg8 = %c0 to %c512 step %c256 {
      %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.textract ins(%24, %c0, %arg8 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%33 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %34 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
      pto.textract ins(%32, %arg8, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%34 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %35 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %36 = arith.addi %arg8, %c128 : index
      pto.textract ins(%24, %c0, %36 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%35 : !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %37 = pto.alloc_tile addr = %c24576_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>
      %38 = arith.addi %arg8, %c128 : index
      pto.textract ins(%32, %38, %c0 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>, index, index) outs(%37 : !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %39 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%39, %33, %34 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %40 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c32 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%40, %35, %37 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x32xbf16, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
  }
  %13 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %c0, %10], sizes = [%c1, %c1, %c1, %c128, %c32] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%11 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%13 : !pto.partition_tensor_view<1x1x1x128x32xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %14 = pto.partition_view %4, offsets = [%c0, %c0, %c0, %c0, %10], sizes = [%c1, %c1, %c1, %c128, %c32] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%12 : !pto.tile_buf<acc, 128x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%14 : !pto.partition_tensor_view<1x1x1x128x32xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

