// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @kv_score_proj_0(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<bf16, gm>, %arg3: !pto.ptr<f32, gm>, %arg4: !pto.ptr<f32, gm>, %arg5: i32, %arg6: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c1048576 = arith.constant 1048576 : index
  %c0_i64 = arith.constant 0 : i64
  %c2048_i64 = arith.constant 2048 : i64
  %c81920_i64 = arith.constant 81920 : i64
  %c98304_i64 = arith.constant 98304 : i64
  %c131072_i64 = arith.constant 131072 : i64
  %c16384_i64 = arith.constant 16384 : i64
  %c49152_i64 = arith.constant 49152 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c8 = arith.constant 8 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c256 = arith.constant 256 : index
  %c16 = arith.constant 16 : index
  %c32 = arith.constant 32 : index
  %c0 = arith.constant 0 : index
  %c2 = arith.constant 2 : index
  %c512 = arith.constant 512 : index
  %c32768 = arith.constant 32768 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c8, %c4096], strides = [%c32768, %c32768, %c32768, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c256, %c4096], strides = [%c1048576, %c1048576, %c1048576, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c256, %c4096], strides = [%c1048576, %c1048576, %c1048576, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %3 = pto.make_tensor_view %arg3, shape = [%c1, %c1, %c1, %c16, %c256], strides = [%c4096, %c4096, %c4096, %c256, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %4 = pto.make_tensor_view %arg4, shape = [%c1, %c1, %c1, %c16, %c256], strides = [%c4096, %c4096, %c4096, %c256, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %5 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %6 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %7 = arith.index_cast %arg5 : i32 to index
  %8 = arith.divsi %7, %c8 : index
  %9 = arith.muli %8, %c16 : index
  %10 = arith.remsi %7, %c8 : index
  %11 = arith.muli %10, %c32 : index
  %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %13 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  scf.for %arg7 = %c0 to %c8 step %c2 {
    %16 = arith.muli %arg7, %c512 : index
    %17 = arith.subi %c8, %9 : index
    %18 = arith.muli %arg7, %c512 : index
    %19 = arith.addi %18, %c512 : index
    %20 = arith.subi %c8, %9 : index
    %21 = pto.alloc_tile addr = %c81920_i64 valid_row = %17 valid_col = %c512 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %22 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %9, %16], sizes = [%c1, %c1, %c1, %17, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x?x512xbf16>) outs(%21 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %23 = pto.alloc_tile addr = %c98304_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %24 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %11, %16], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%24 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%23 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %25 = pto.alloc_tile addr = %c131072_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %26 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %16], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%26 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%25 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %27 = pto.alloc_tile addr = %c0_i64 valid_row = %20 valid_col = %c512 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %28 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %9, %19], sizes = [%c1, %c1, %c1, %20, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%28 : !pto.partition_tensor_view<1x1x1x?x512xbf16>) outs(%27 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %29 = pto.alloc_tile addr = %c16384_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %30 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %11, %19], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%30 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%29 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %31 = pto.alloc_tile addr = %c49152_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %32 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %11, %19], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%32 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%31 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %33 = arith.cmpi eq, %16, %c0 : index
    scf.if %33 {
      %41 = pto.alloc_tile addr = %c98304_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %42 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c512 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tmov ins(%21 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%42 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %43 = pto.alloc_tile addr = %c0_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%41 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%43 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%42, %43 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%44 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %45 = pto.alloc_tile addr = %c131072_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %46 = pto.alloc_tile addr = %c0_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%45 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%46 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %47 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul ins(%42, %46 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%47 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    } else {
      %41 = pto.alloc_tile addr = %c98304_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %42 = pto.alloc_tile addr = %c0_i64 valid_row = %17 valid_col = %c512 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tmov ins(%21 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%42 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %43 = pto.alloc_tile addr = %c0_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%41 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%43 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%44, %42, %43 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%44 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %45 = pto.alloc_tile addr = %c131072_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
      %46 = pto.alloc_tile addr = %c0_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
      pto.tmov ins(%45 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%46 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %47 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      pto.tmatmul.acc ins(%47, %42, %46 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%47 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
    %34 = pto.alloc_tile addr = %c16384_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
    %35 = pto.alloc_tile addr = %c16384_i64 valid_row = %20 valid_col = %c512 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%27 : !pto.tile_buf<mat, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) outs(%35 : !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %36 = pto.alloc_tile addr = %c32768_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
    pto.tmov ins(%34 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%36 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %37 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%37, %35, %36 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%37 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %38 = pto.alloc_tile addr = %c49152_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>
    %39 = pto.alloc_tile addr = %c32768_i64 valid_row = %c512 valid_col = %c32 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>
    pto.tmov ins(%38 : !pto.tile_buf<mat, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %40 = pto.alloc_tile addr = %c2048_i64 valid_row = %c16 valid_col = %c32 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%40, %35, %39 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 512x32xbf16, valid=?x?, slayout=col_major>) outs(%40 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  %14 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %9, %11], sizes = [%c1, %c1, %c1, %c16, %c32] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%12 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%14 : !pto.partition_tensor_view<1x1x1x16x32xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %15 = pto.partition_view %4, offsets = [%c0, %c0, %c0, %9, %11], sizes = [%c1, %c1, %c1, %c16, %c32] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%13 : !pto.tile_buf<acc, 16x32xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%15 : !pto.partition_tensor_view<1x1x1x16x32xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

