// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @idx_qr_proj_matmul(%arg0: !pto.ptr<i32, gm>, %arg1: !pto.ptr<i8, gm>, %arg2: !pto.ptr<i8, gm>, %arg3: i32, %arg4: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c8388608 = arith.constant 8388608 : index
  %c0_i64 = arith.constant 0 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c135168_i64 = arith.constant 135168 : i64
  %c139264_i64 = arith.constant 139264 : i64
  %c3072_i64 = arith.constant 3072 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c1024_i64 = arith.constant 1024 : i64
  %c2048_i64 = arith.constant 2048 : i64
  %c16 = arith.constant 16 : index
  %c8192 = arith.constant 8192 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c1024 = arith.constant 1024 : index
  %c0 = arith.constant 0 : index
  %c512 = arith.constant 512 : index
  %c4 = arith.constant 4 : index
  %c2 = arith.constant 2 : index
  %c256 = arith.constant 256 : index
  %c128 = arith.constant 128 : index
  %c64 = arith.constant 64 : index
  %c131072 = arith.constant 131072 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c16, %c8192], strides = [%c131072, %c131072, %c131072, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi32>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8, %c1024], strides = [%c8192, %c8192, %c8192, %c1024, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c1024, %c8192], strides = [%c8388608, %c8388608, %c8388608, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %3 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %4 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %5 = arith.index_cast %arg3 : i32 to index
  %6 = arith.muli %5, %c1024 : index
  scf.for %arg5 = %c0 to %c1024 step %c512 {
    %7 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    scf.for %arg6 = %c0 to %c4 step %c2 {
      %10 = arith.muli %arg6, %c256 : index
      %11 = arith.muli %arg6, %c256 : index
      %12 = arith.addi %11, %c256 : index
      %13 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %14 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %10], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%14 : !pto.partition_tensor_view<1x1x1x8x256xi8>) outs(%13 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %15 = pto.alloc_tile addr = %c4096_i64 valid_row = %c256 valid_col = %c512 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %16 = arith.addi %6, %arg5 : index
      %17 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %10, %16], sizes = [%c1, %c1, %c1, %c256, %c512] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%17 : !pto.partition_tensor_view<1x1x1x256x512xi8>) outs(%15 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %18 = pto.alloc_tile addr = %c135168_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %19 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %12], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%19 : !pto.partition_tensor_view<1x1x1x8x256xi8>) outs(%18 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %20 = pto.alloc_tile addr = %c139264_i64 valid_row = %c256 valid_col = %c512 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>
      %21 = arith.addi %6, %arg5 : index
      %22 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %12, %21], sizes = [%c1, %c1, %c1, %c256, %c512] : !pto.tensor_view<1x1x1x?x?xi8>
      pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x256x512xi8>) outs(%20 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %23 = arith.cmpi eq, %10, %c0 : index
      scf.if %23 {
        %24 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        scf.for %arg7 = %c0 to %c256 step %c128 {
          %25 = pto.alloc_tile addr = %c3072_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
          pto.textract ins(%13, %c0, %arg7 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%25 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
          pto.textract ins(%15, %arg7, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
          %28 = arith.addi %arg7, %c64 : index
          pto.textract ins(%13, %c0, %28 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%27 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %29 = pto.alloc_tile addr = %c32768_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
          %30 = arith.addi %arg7, %c64 : index
          pto.textract ins(%15, %30, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%29 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %31 = arith.cmpi eq, %arg7, %c0 : index
          scf.if %31 {
            %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
            pto.tmatmul ins(%25, %26 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%33 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          } else {
            %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
            pto.tmatmul.acc ins(%33, %25, %26 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%33 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          }
          %32 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%32, %27, %29 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%32 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
      } else {
        scf.for %arg7 = %c0 to %c256 step %c128 {
          %24 = pto.alloc_tile addr = %c3072_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
          pto.textract ins(%13, %c0, %arg7 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%24 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %25 = pto.alloc_tile addr = %c0_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
          pto.textract ins(%15, %arg7, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%25 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
          %27 = arith.addi %arg7, %c64 : index
          pto.textract ins(%13, %c0, %27 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %28 = pto.alloc_tile addr = %c32768_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
          %29 = arith.addi %arg7, %c64 : index
          pto.textract ins(%15, %29, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%28 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %30 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%30, %24, %25 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%30 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
          %31 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%31, %26, %28 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%31 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
      }
      scf.for %arg7 = %c0 to %c256 step %c128 {
        %24 = pto.alloc_tile addr = %c1024_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%18, %c0, %arg7 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%24 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %25 = pto.alloc_tile addr = %c0_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
        pto.textract ins(%20, %arg7, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%25 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %26 = pto.alloc_tile addr = %c2048_i64 valid_row = %c8 valid_col = %c64 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>
        %27 = arith.addi %arg7, %c64 : index
        pto.textract ins(%18, %c0, %27 : !pto.tile_buf<mat, 16x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%26 : !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %28 = pto.alloc_tile addr = %c32768_i64 valid_row = %c64 valid_col = %c512 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>
        %29 = arith.addi %arg7, %c64 : index
        pto.textract ins(%20, %29, %c0 : !pto.tile_buf<mat, 256x512xi8, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%28 : !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %30 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%30, %24, %25 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%30 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %31 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%31, %26, %28 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x64xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 64x512xi8, valid=?x?, slayout=col_major>) outs(%31 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
    }
    %8 = arith.addi %6, %arg5 : index
    %9 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %8], sizes = [%c1, %c1, %c1, %c16, %c512] : !pto.tensor_view<1x1x1x?x?xi32>
    pto.tstore ins(%7 : !pto.tile_buf<acc, 16x512xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%9 : !pto.partition_tensor_view<1x1x1x16x512xi32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  return
}

