// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @qk_pv_aic(%arg0: !pto.ptr<f32, gm>, %arg1: !pto.ptr<f32, gm>, %arg2: !pto.ptr<f32, gm>, %arg3: !pto.ptr<bf16, gm>, %arg4: !pto.ptr<f32, gm>, %arg5: !pto.ptr<bf16, gm>, %arg6: i32, %arg7: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c144 = arith.constant 144 : index
  %c96 = arith.constant 96 : index
  %c48 = arith.constant 48 : index
  %c4194304 = arith.constant 4194304 : index
  %c25165824 = arith.constant 25165824 : index
  %c12582912 = arith.constant 12582912 : index
  %c65536_i64 = arith.constant 65536 : i64
  %c196608_i64 = arith.constant 196608 : i64
  %c327680_i64 = arith.constant 327680 : i64
  %c0_i64 = arith.constant 0 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c24576 = arith.constant 24576 : index
  %c1 = arith.constant 1 : index
  %c512 = arith.constant 512 : index
  %c49152 = arith.constant 49152 : index
  %c128 = arith.constant 128 : index
  %c384 = arith.constant 384 : index
  %c8192 = arith.constant 8192 : index
  %c192 = arith.constant 192 : index
  %c0 = arith.constant 0 : index
  %c3 = arith.constant 3 : index
  %c64 = arith.constant 64 : index
  %c32 = arith.constant 32 : index
  %c256 = arith.constant 256 : index
  %c16 = arith.constant 16 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c24576, %c1], strides = [%c24576, %c24576, %c24576, %c1, %c24576] {layout = #pto.layout<dn>} : !pto.tensor_view<1x1x1x?x?xf32>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c24576, %c1], strides = [%c24576, %c24576, %c24576, %c1, %c24576] {layout = #pto.layout<dn>} : !pto.tensor_view<1x1x1x?x?xf32>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c24576, %c512], strides = [%c12582912, %c12582912, %c12582912, %c512, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %3 = pto.make_tensor_view %arg3, shape = [%c1, %c1, %c1, %c49152, %c512], strides = [%c25165824, %c25165824, %c25165824, %c512, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %4 = pto.make_tensor_view %arg4, shape = [%c1, %c1, %c1, %c128, %c384], strides = [%c49152, %c49152, %c49152, %c384, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %5 = pto.make_tensor_view %arg5, shape = [%c1, %c1, %c1, %c8192, %c512], strides = [%c4194304, %c4194304, %c4194304, %c512, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %6 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %7 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %8 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %9 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %10 = pto.reserve_buffer{name = "qk_pv_v2c_slot_buffer", size = 65536, location = <mat>, auto = false, base = 0} -> i32
  %11 = pto.import_reserved_buffer{name = "qk_pv_c2v_slot_buffer", peer_func = @qk_pv_aiv} -> i32
  %12 = pto.initialize_l2l_pipe{dir_mask = 3, slot_size = 16384, slot_num = 4, nosplit = true} (%11 : i32, %10 : i32) {__pto.frontend_id = 0 : i32} -> !pto.pipe
  %13 = arith.index_cast %arg6 : i32 to index
  %14 = arith.cmpi slt, %13, %c128 : index
  scf.if %14 {
    %15 = arith.muli %13, %c384 : index
    %16 = arith.muli %13, %c192 : index
    scf.for %arg8 = %c0 to %c3 step %c1 {
      %17 = arith.muli %arg8, %c128 : index
      %18 = arith.addi %15, %17 : index
      %19 = pto.alloc_tile addr = %c65536_i64 valid_row = %c128 valid_col = %c512 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %20 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %18, %c0], sizes = [%c1, %c1, %c1, %c128, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%20 : !pto.partition_tensor_view<1x1x1x128x512xbf16>) outs(%19 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %21 = pto.alloc_tile addr = %c196608_i64 valid_row = %c128 valid_col = %c512 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %22 = pto.partition_view %3, offsets = [%c0, %c0, %c0, %18, %c0], sizes = [%c1, %c1, %c1, %c128, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x128x512xbf16>) outs(%21 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %23 = arith.muli %13, %c64 : index
      %24 = pto.alloc_tile addr = %c327680_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %25 = pto.partition_view %5, offsets = [%c0, %c0, %c0, %23, %c0], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%25 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%24 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %26 = pto.alloc_tile addr = %c65536_i64 valid_row = %c512 valid_col = %c128 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>
      %27 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      scf.for %arg9 = %c0 to %c512 step %c256 {
        %61 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%24, %c0, %arg9 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%61 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%26, %arg9, %c0 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%62 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %63 = pto.alloc_tile addr = %c8192_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %64 = arith.addi %arg9, %c128 : index
        pto.textract ins(%24, %c0, %64 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%63 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %65 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        %66 = arith.addi %arg9, %c128 : index
        pto.textract ins(%26, %66, %c0 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%65 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %67 = arith.cmpi eq, %arg9, %c0 : index
        scf.if %67 {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%61, %62 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%69, %61, %62 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %68 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%68, %63, %65 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%68 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      pto.tpush(%27, %12 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.pipe) {split = 0}
      %28 = arith.muli %13, %c64 : index
      %29 = arith.addi %28, %c32 : index
      %30 = pto.alloc_tile addr = %c327680_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      %31 = pto.partition_view %5, offsets = [%c0, %c0, %c0, %29, %c0], sizes = [%c1, %c1, %c1, %c32, %c512] : !pto.tensor_view<1x1x1x?x?xbf16>
      pto.tload ins(%31 : !pto.partition_tensor_view<1x1x1x32x512xbf16>) outs(%30 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %32 = pto.alloc_tile addr = %c65536_i64 valid_row = %c512 valid_col = %c128 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>
      %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      scf.for %arg9 = %c0 to %c512 step %c256 {
        %61 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%30, %c0, %arg9 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%61 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%32, %arg9, %c0 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%62 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %63 = pto.alloc_tile addr = %c8192_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %64 = arith.addi %arg9, %c128 : index
        pto.textract ins(%30, %c0, %64 : !pto.tile_buf<mat, 32x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%63 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %65 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
        %66 = arith.addi %arg9, %c128 : index
        pto.textract ins(%32, %66, %c0 : !pto.tile_buf<mat, 512x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%65 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %67 = arith.cmpi eq, %arg9, %c0 : index
        scf.if %67 {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%61, %62 : !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%69, %61, %62 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %68 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c128 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%68, %63, %65 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%68 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      pto.tpush(%33, %12 : !pto.tile_buf<acc, 32x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.pipe) {split = 0}
      %34 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %35 = pto.declare_tile -> !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tpop(%35, %12 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.pipe) {split = 0}
      scf.for %arg9 = %c0 to %c128 step %c64 {
        %61 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%35, %c0, %arg9 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%61 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%21, %arg9, %c0 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%62 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %63 = pto.alloc_tile addr = %c8192_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %64 = arith.addi %arg9, %c32 : index
        pto.textract ins(%35, %c0, %64 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%63 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %65 = pto.alloc_tile addr = %c32768_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>
        %66 = arith.addi %arg9, %c32 : index
        pto.textract ins(%21, %66, %c0 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%65 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %67 = arith.cmpi eq, %arg9, %c0 : index
        scf.if %67 {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%61, %62 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%69, %61, %62 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %68 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%68, %63, %65 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%68 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      pto.tfree(%12 : !pto.pipe) {split = 0}
      %36 = arith.muli %arg8, %c16 : index
      %37 = arith.addi %16, %36 : index
      %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %39 = pto.subview %34[%c0, %c0] sizes [16, 512] : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024> -> !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>
      %40 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %37, %c0], sizes = [%c1, %c1, %c1, %c16, %c512] : !pto.tensor_view<1x1x1x?x?xf32>
      pto.tstore ins(%39 : !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>) outs(%40 : !pto.partition_tensor_view<1x1x1x16x512xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %41 = arith.addi %16, %c48 : index
      %42 = arith.muli %arg8, %c16 : index
      %43 = arith.addi %41, %42 : index
      %44 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %45 = pto.subview %34[%c16, %c0] sizes [16, 512] : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024> -> !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>
      %46 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %43, %c0], sizes = [%c1, %c1, %c1, %c16, %c512] : !pto.tensor_view<1x1x1x?x?xf32>
      pto.tstore ins(%45 : !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>) outs(%46 : !pto.partition_tensor_view<1x1x1x16x512xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %47 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %48 = pto.declare_tile -> !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
      pto.tpop(%48, %12 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.pipe) {split = 0}
      scf.for %arg9 = %c0 to %c128 step %c64 {
        %61 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        pto.textract ins(%48, %c0, %arg9 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%61 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>
        pto.textract ins(%21, %arg9, %c0 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%62 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %63 = pto.alloc_tile addr = %c8192_i64 valid_row = %c32 valid_col = %c32 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>
        %64 = arith.addi %arg9, %c32 : index
        pto.textract ins(%48, %c0, %64 : !pto.tile_buf<mat, 32x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%63 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %65 = pto.alloc_tile addr = %c32768_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>
        %66 = arith.addi %arg9, %c32 : index
        pto.textract ins(%21, %66, %c0 : !pto.tile_buf<mat, 128x512xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%65 : !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        %67 = arith.cmpi eq, %arg9, %c0 : index
        scf.if %67 {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul ins(%61, %62 : !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        } else {
          %69 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
          pto.tmatmul.acc ins(%69, %61, %62 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%69 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
        }
        %68 = pto.alloc_tile addr = %c0_i64 valid_row = %c32 valid_col = %c512 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
        pto.tmatmul.acc ins(%68, %63, %65 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 32x32xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 32x512xbf16, valid=?x?, slayout=col_major>) outs(%68 : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      }
      pto.tfree(%12 : !pto.pipe) {split = 0}
      %49 = arith.addi %16, %c96 : index
      %50 = arith.muli %arg8, %c16 : index
      %51 = arith.addi %49, %50 : index
      %52 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %53 = pto.subview %47[%c0, %c0] sizes [16, 512] : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024> -> !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>
      %54 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %51, %c0], sizes = [%c1, %c1, %c1, %c16, %c512] : !pto.tensor_view<1x1x1x?x?xf32>
      pto.tstore ins(%53 : !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>) outs(%54 : !pto.partition_tensor_view<1x1x1x16x512xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
      %55 = arith.addi %16, %c144 : index
      %56 = arith.muli %arg8, %c16 : index
      %57 = arith.addi %55, %56 : index
      %58 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c512 : !pto.tile_buf<acc, 16x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
      %59 = pto.subview %47[%c16, %c0] sizes [16, 512] : !pto.tile_buf<acc, 32x512xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024> -> !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>
      %60 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %57, %c0], sizes = [%c1, %c1, %c1, %c16, %c512] : !pto.tensor_view<1x1x1x?x?xf32>
      pto.tstore ins(%59 : !pto.tile_buf<acc, 16x512xf32, blayout=col_major, slayout=row_major, fractal=1024>) outs(%60 : !pto.partition_tensor_view<1x1x1x16x512xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    }
  } else {
  }
  return
}
