// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @proj_a_mm(%arg0: !pto.ptr<bf16, gm>, %arg1: !pto.ptr<bf16, gm>, %arg2: !pto.ptr<f32, gm>, %arg3: index, %arg4: index, %arg5: index, %arg6: i32, %arg7: i32) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c33554432 = arith.constant 33554432 : index
  %c131072 = arith.constant 131072 : index
  %c4194304 = arith.constant 4194304 : index
  %c16384_i64 = arith.constant 16384 : i64
  %c81920_i64 = arith.constant 81920 : i64
  %c0_i64 = arith.constant 0 : i64
  %c8192_i64 = arith.constant 8192 : i64
  %c12288_i64 = arith.constant 12288 : i64
  %c32768_i64 = arith.constant 32768 : i64
  %c4096_i64 = arith.constant 4096 : i64
  %c64 = arith.constant 64 : index
  %c4096 = arith.constant 4096 : index
  %c1 = arith.constant 1 : index
  %c8 = arith.constant 8 : index
  %c1024 = arith.constant 1024 : index
  %c16 = arith.constant 16 : index
  %c8192 = arith.constant 8192 : index
  %c128 = arith.constant 128 : index
  %c256 = arith.constant 256 : index
  %c0 = arith.constant 0 : index
  %c15 = arith.constant 15 : index
  %c2 = arith.constant 2 : index
  %c3840 = arith.constant 3840 : index
  %c262144 = arith.constant 262144 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c64, %c4096], strides = [%c262144, %c262144, %c262144, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %1 = pto.make_tensor_view %arg1, shape = [%c8, %c1024, %c4096], strides = [%c4194304, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<?x?x?xbf16>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c16, %c8192], strides = [%c131072, %c131072, %c131072, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xf32>
  %3 = arith.index_cast %arg6 : i32 to index
  %4 = arith.muli %3, %c128 : index
  %5 = pto.alloc_tile addr = %c16384_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %6 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %c0], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%6 : !pto.partition_tensor_view<1x1x1x8x256xbf16>) outs(%5 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %7 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %8 = pto.alloc_tile addr = %c81920_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %9 = arith.muli %arg4, %c1024 : index
  %10 = arith.addi %9, %4 : index
  %11 = pto.partition_view %7, offsets = [%c0, %c0, %c0, %10, %c0], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%11 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%8 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %12 = pto.alloc_tile addr = %c81920_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
  %13 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %14 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%5, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%14 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %15 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%12, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%15 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %16 = pto.alloc_tile addr = %c12288_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%5, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%16 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %17 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%12, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%17 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %18 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul ins(%14, %15 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%18 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %19 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%19, %16, %17 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%19 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  scf.for %arg8 = %c1 to %c15 step %c2 {
    %37 = arith.muli %arg8, %c256 : index
    %38 = arith.muli %arg8, %c256 : index
    %39 = arith.addi %38, %c256 : index
    %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %41 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %37], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%41 : !pto.partition_tensor_view<1x1x1x8x256xbf16>) outs(%40 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %42 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %43 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %39], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%43 : !pto.partition_tensor_view<1x1x1x8x256xbf16>) outs(%42 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %44 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
    %45 = pto.alloc_tile addr = %c81920_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %46 = arith.muli %arg4, %c1024 : index
    %47 = arith.addi %46, %4 : index
    %48 = pto.partition_view %44, offsets = [%c0, %c0, %c0, %47, %37], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%48 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%45 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %49 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
    %50 = pto.alloc_tile addr = %c16384_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    %51 = arith.muli %arg4, %c1024 : index
    %52 = arith.addi %51, %4 : index
    %53 = pto.partition_view %49, offsets = [%c0, %c0, %c0, %52, %39], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
    pto.tload ins(%53 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%50 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %54 = pto.alloc_tile addr = %c81920_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
    %55 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%40, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%55 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %56 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%54, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%56 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %57 = pto.alloc_tile addr = %c12288_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%40, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%57 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %58 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%54, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%58 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %59 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%59, %55, %56 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%59 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %60 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%60, %57, %58 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%60 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %61 = pto.alloc_tile addr = %c16384_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
    %62 = pto.alloc_tile addr = %c0_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%42, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%62 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %63 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%61, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%63 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %64 = pto.alloc_tile addr = %c4096_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
    pto.textract ins(%42, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%64 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %65 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
    pto.textract ins(%61, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%65 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %66 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%66, %62, %63 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%66 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %67 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%67, %64, %65 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%67 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  %20 = pto.alloc_tile addr = %c16384_i64 valid_row = %c8 valid_col = %c256 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %21 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %arg3, %c3840], sizes = [%c1, %c1, %c1, %c8, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%21 : !pto.partition_tensor_view<1x1x1x8x256xbf16>) outs(%20 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %22 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c8192, %c4096], strides = [%c33554432, %c33554432, %c33554432, %c4096, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xbf16>
  %23 = pto.alloc_tile addr = %c81920_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  %24 = arith.muli %arg4, %c1024 : index
  %25 = arith.addi %24, %4 : index
  %26 = pto.partition_view %22, offsets = [%c0, %c0, %c0, %25, %c3840], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xbf16>
  pto.tload ins(%26 : !pto.partition_tensor_view<1x1x1x128x256xbf16>) outs(%23 : !pto.tile_buf<mat, 128x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %27 = pto.alloc_tile addr = %c81920_i64 valid_row = %c256 valid_col = %c128 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>
  %28 = pto.alloc_tile addr = %c8192_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%20, %c0, %c0 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%28 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %29 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%27, %c0, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%29 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %30 = pto.alloc_tile addr = %c12288_i64 valid_row = %c8 valid_col = %c128 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>
  pto.textract ins(%20, %c0, %c128 : !pto.tile_buf<mat, 16x256xbf16, valid=?x?, blayout=col_major, slayout=row_major>, index, index) outs(%30 : !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 1 : i64, loop_depth = 1 : i64, name = "template_textract_mat2left", postupdate = 0 : i64, tags = ["move", "extract", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %31 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c128 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>
  pto.textract ins(%27, %c128, %c0 : !pto.tile_buf<mat, 256x128xbf16, valid=?x?, slayout=col_major>, index, index) outs(%31 : !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) {candidates = [{id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 4 : i64, loop_depth = 1 : i64, name = "template_textract_mat2right_trans", postupdate = 0 : i64, tags = ["move", "extract", "mat", "right", "transpose"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %32 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%32, %28, %29 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%32 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %33 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  pto.tmatmul.acc ins(%33, %30, %31 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 16x128xbf16, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 128x128xbf16, valid=?x?, slayout=col_major>) outs(%33 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  %34 = pto.alloc_tile addr = %c0_i64 valid_row = %c16 valid_col = %c128 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
  %35 = arith.addi %arg5, %4 : index
  %36 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %c0, %35], sizes = [%c1, %c1, %c1, %c16, %c128] : !pto.tensor_view<1x1x1x?x?xf32>
  pto.tstore ins(%34 : !pto.tile_buf<acc, 16x128xf32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%36 : !pto.partition_tensor_view<1x1x1x16x128xf32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  return
}

