// -----// IR Dump After PTOFusionRegionGen (pto-fusion-region-gen) //----- //
func.func @proj_b_mm(%arg0: !pto.ptr<i32, gm>, %arg1: !pto.ptr<i8, gm>, %arg2: !pto.ptr<i8, gm>, %arg3: index, %arg4: index, %arg5: index) attributes {pto.kernel_kind = #pto.kernel_kind<cube>} {
  %c33554432 = arith.constant 33554432 : index
  %c1048576 = arith.constant 1048576 : index
  %c32768_i64 = arith.constant 32768 : i64
  %c98304_i64 = arith.constant 98304 : i64
  %c0_i64 = arith.constant 0 : i64
  %c163840_i64 = arith.constant 163840 : i64
  %c128 = arith.constant 128 : index
  %c32768 = arith.constant 32768 : index
  %c1 = arith.constant 1 : index
  %c8192 = arith.constant 8192 : index
  %c4096 = arith.constant 4096 : index
  %c0 = arith.constant 0 : index
  %c4 = arith.constant 4 : index
  %c256 = arith.constant 256 : index
  %c512 = arith.constant 512 : index
  %c768 = arith.constant 768 : index
  %c4194304 = arith.constant 4194304 : index
  %0 = pto.make_tensor_view %arg0, shape = [%c1, %c1, %c1, %c128, %c32768], strides = [%c4194304, %c4194304, %c4194304, %c32768, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi32>
  %1 = pto.make_tensor_view %arg1, shape = [%c1, %c1, %c1, %c128, %c8192], strides = [%c1048576, %c1048576, %c1048576, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  %2 = pto.make_tensor_view %arg2, shape = [%c1, %c1, %c1, %c4096, %c8192], strides = [%c33554432, %c33554432, %c33554432, %c8192, %c1] {layout = #pto.layout<nd>} : !pto.tensor_view<1x1x1x?x?xi8>
  scf.for %arg6 = %c0 to %c4 step %c1 {
    %3 = arith.muli %arg6, %c256 : index
    %4 = arith.addi %arg3, %3 : index
    %5 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %6 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %arg4], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%6 : !pto.partition_tensor_view<1x1x1x128x256xi8>) outs(%5 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %7 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %8 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %4, %arg4], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%8 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%7 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %9 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
    %10 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%5 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) outs(%10 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %11 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>
    pto.tmov ins(%9 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>) outs(%11 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %12 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul ins(%10, %11 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) outs(%12 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul", postupdate = 0 : i64, tags = ["cube", "matmul"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %13 = arith.addi %arg4, %c256 : index
    %14 = arith.addi %arg4, %c512 : index
    %15 = pto.alloc_tile addr = %c163840_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %16 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %13], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%16 : !pto.partition_tensor_view<1x1x1x128x256xi8>) outs(%15 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %17 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %18 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %4, %13], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%18 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%17 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %19 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %20 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %14], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%20 : !pto.partition_tensor_view<1x1x1x128x256xi8>) outs(%19 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %21 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %22 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %4, %14], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%22 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%21 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %23 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
    %24 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%15 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) outs(%24 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %25 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>
    pto.tmov ins(%23 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>) outs(%25 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %26 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%26, %24, %25 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) outs(%26 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %27 = pto.alloc_tile addr = %c32768_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
    %28 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%19 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) outs(%28 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %29 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>
    pto.tmov ins(%27 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>) outs(%29 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %30 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%30, %28, %29 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) outs(%30 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %31 = arith.addi %arg4, %c768 : index
    %32 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %33 = pto.partition_view %1, offsets = [%c0, %c0, %c0, %c0, %31], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%33 : !pto.partition_tensor_view<1x1x1x128x256xi8>) outs(%32 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %34 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    %35 = pto.partition_view %2, offsets = [%c0, %c0, %c0, %4, %31], sizes = [%c1, %c1, %c1, %c256, %c256] : !pto.tensor_view<1x1x1x?x?xi8>
    pto.tload ins(%35 : !pto.partition_tensor_view<1x1x1x256x256xi8>) outs(%34 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, {id = 4 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_dn2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "dn2nz"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tload_gm_to_mat_nd2nz", postupdate = 0 : i64, tags = ["load", "gm", "mat", "nd2nz"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %36 = pto.alloc_tile addr = %c98304_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>
    %37 = pto.alloc_tile addr = %c32768_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>
    pto.tmov ins(%32 : !pto.tile_buf<mat, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) outs(%37 : !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>) {candidates = [{id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 2 : i64, loop_depth = 1 : i64, name = "template_tmov_m2l", postupdate = 0 : i64, tags = ["move", "mat", "left"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %38 = pto.alloc_tile addr = %c0_i64 valid_row = %c256 valid_col = %c256 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>
    pto.tmov ins(%36 : !pto.tile_buf<mat, 256x256xi8, valid=?x?, slayout=col_major>) outs(%38 : !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) {candidates = [{id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 1 : i64, name = "template_tmov_m2r", postupdate = 0 : i64, tags = ["move", "mat", "right"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %39 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    pto.tmatmul.acc ins(%39, %37, %38 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>, !pto.tile_buf<left, 128x256xi8, valid=?x?, blayout=col_major, slayout=row_major>, !pto.tile_buf<right, 256x256xi8, valid=?x?, slayout=col_major>) outs(%39 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) {candidates = [{id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}], pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 0 : i64, loop_depth = 1 : i64, name = "template_tmatmul_acc", postupdate = 0 : i64, tags = ["cube", "matmul", "acc"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
    %40 = pto.alloc_tile addr = %c0_i64 valid_row = %c128 valid_col = %c256 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>
    %41 = arith.muli %arg5, %c4096 : index
    %42 = arith.addi %41, %4 : index
    %43 = pto.partition_view %0, offsets = [%c0, %c0, %c0, %c0, %42], sizes = [%c1, %c1, %c1, %c128, %c256] : !pto.tensor_view<1x1x1x?x?xi32>
    pto.tstore ins(%40 : !pto.tile_buf<acc, 128x256xi32, valid=?x?, blayout=col_major, slayout=row_major, fractal=1024>) outs(%43 : !pto.partition_tensor_view<1x1x1x128x256xi32>) {candidates = [{id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}], layout = #pto.layout<nd>, pto.tilelib.impl = "ptodsl", pto.tilelib.selected_candidate = {id = 3 : i64, loop_depth = 0 : i64, name = "template_tstore_acc_to_gm_nz2nd", postupdate = 0 : i64, tags = ["store", "acc", "gm", "nz2nd"], tail = 0 : i64}, pto.vmi.fusion.boundary = "hard", pto.vmi.fusion.boundary_reason = "non_vmi_hard_boundary_fallback"}
  }
  return
}

